variables:
  NO_ISOLATE: 1

stages:
  - build
  - test

.install-sqlite: &install-sqlite
  before_script:
    - apt-get update -y
    - apt-get install -y sqlite3 libsqlite3-dev

build:
  stage: build
  image: jiegec/rust:1.89-bookworm-tuna
  <<: *install-sqlite
  script:
    - cargo build

basic-test:
  stage: test
  image: jiegec/rust:1.89-bookworm-tuna
  <<: *install-sqlite
  script:
    - cargo test --test basic_requirements -- --test-threads=1
  artifacts:
    paths:
      - tests/cases/*.std*
      - tests/cases/*.http
    expire_in: 1 year
    when: always

advanced-test:
  stage: test
  image: jiegec/rust:1.89-bookworm-tuna
  allow_failure: true
  <<: *install-sqlite
  script:
    - cargo test --test advanced_requirements -- --test-threads=1
  artifacts:
    paths:
      - tests/cases/*.std*
      - tests/cases/*.http
    expire_in: 1 year
    when: always

fmt:
  stage: test
  image: jiegec/rust:1.89-bookworm-tuna
  script:
    - cargo fmt --all --check

clippy:
  stage: test
  image: jiegec/rust:1.89-bookworm-tuna
  script:
    - cargo clippy -- -D warnings
